[options]
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo123
admin_passwd = admin123
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/var/lib/odoo/addons/17.0,/mnt/extra-addons
data_dir = /var/lib/odoo
logfile = /var/log/odoo/odoo.log
log_level = warn
